### ISSUE TITLE
Background turned dark, but it didn't work for the texts

### ISSUE THREAD

**Issue by TomBener** [sandoche/Darkmode.js#29]
Hi, thanks for your work!

I used Darkmode.js to add dark mode for my [blog](https://tomben.me) powered by [VuePress](https://github.com/vuejs/vuepress). But in the dark mode, only the background turned black, while the text didn't change at all, like the screenshot below, which looked very weird. In the meanwhile, the button didn't appear the emoji 🌓 I added.

![example](https://user-images.githubusercontent.com/49151155/71175315-3952de80-22a2-11ea-80ea-b7925f54d3ac.png)

And I used the script as your instruction shows:

1. Using NPM
```
npm install darkmode-js
```

2. Add the javascript code and options:
```
// Dark Mode
import Darkmode from 'darkmode-js';

new Darkmode().showWidget();

var options = {
    label: '🌓'
}
  
const darkmode = new Darkmode(options);
darkmode.showWidget();
```

It would be great if you can help me about the problem. Thanks in advance 😊

**Comment by robertnicjoo** [comment]
same issue here, bootstrap card backgrounds won't change

**Comment by robertnicjoo** [comment]
@TomBener I managed to fix my issue with `css` here is my code you may need to edit as your need

```css
.darkmode--activated p, .darkmode--activated h1, .darkmode--activated h2, .darkmode--activated h3, .darkmode--activated h4, .darkmode--activated h5, .darkmode--activated h6, .darkmode--activated span, .darkmode--activated ul, .darkmode--activated li, .darkmode--activated i, .darkmode--activated label, .darkmode--activated span{
        color: #fff;
    }
    .darkmode--activated .card{
        background: #000000;
    }
```

**Comment by sandoche** [comment]
I will look into it to put it also in the library if it fits (and with the dynamic variables)

**Comment by LordShenron** [comment]
> @TomBener I managed to fix my issue with `css` here is my code you may need to edit as your need
> 
> ```css
> .darkmode--activated p, .darkmode--activated h1, .darkmode--activated h2, .darkmode--activated h3, .darkmode--activated h4, .darkmode--activated h5, .darkmode--activated h6, .darkmode--activated span, .darkmode--activated ul, .darkmode--activated li, .darkmode--activated i, .darkmode--activated label, .darkmode--activated span{
>         color: #fff;
>     }
>     .darkmode--activated .card{
>         background: #000000;
>     }
> ```

Thanks a bunch, it works fine but the widget is still broken. I added using the jscdn method.

**Comment by robertnicjoo** [comment]
your welcome,
widget isn't broken all you need is to provide icon for it from your main js file, currently I'm with phone to share you the code but if I'm not mistaking it's already in documents.


here in options part

https://github.com/sandoche/Darkmode.js/blob/master/README.md#%EF%B8%8F-options

**Comment by LordShenron** [comment]
well i added a js button instead of using the widget.. work so far.

**Comment by madhavarshney** [comment]
@TomBener @sandoche - It seems like the OP's issue happens because the button and `mix-blend-mode` layer gets covered by subsequent elements. The following code snippet works (not sure if it is the best way though):
```css
.darkmode-toggle, .darkmode-layer {
    z-index: 1;
}
```
@TomBener Try pasting the following snippet in devtools for https://tomben.me/:
```js
let script = document.createElement('script');
script.src = 'https://cdn.jsdelivr.net/npm/darkmode-js@1.5.5/lib/darkmode-js.min.js';
script.onload = () => new Darkmode({ label: '🌓', backgroundColor: '#f6f6f6' }).showWidget();
document.head.appendChild(script);

let style = document.createElement('style');
style.innerText = `
.darkmode-toggle, .darkmode-layer {
    z-index: 1;
}
`;
document.head.appendChild(style);
```
