### ISSUE TITLE
darkmode button

### ISSUE THREAD

**Issue by acegoal07** [sandoche/Darkmode.js#48]
the dark-mode button go behinds images

**Comment by sandoche** [comment]
As documented here you can play on the z-index to make it show again:
https://github.com/sandoche/Darkmode.js#debug

```css
.darkmode-toggle {
  z-index: 500;
}
```
