### ISSUE TITLE
How To Exclude background-image css property

### ISSUE THREAD

**Issue by SubhodipRoy** [sandoche/Darkmode.js#52]
Everything is working fine except making the background image of my page negative. I have added a backround image using css `background-image` peoperty. And now its changing the color of the image. How can can is solve the problem?

Hope for solution soon.

Thanks from reply in advance.

**Comment by sandoche** [comment]
Maybe try this:
```css
.darkmode--activated .class-width-background-image {
  mix-blend-mode: difference;
}
```

Don't forget to replace ".class-width-background-image" with the name of the class.
